### ISSUE TITLE
Stack limit reached ? 

### ISSUE THREAD

**Issue by asdfjohnny1** [sjteresi/TE_Density#142]
Good morning,

I am new to using Python and i keep getting this error when trying to use the "make system_test" 

Traceback (most recent call last):
  File "/Users/immlerlab/Documents/TE/TE_Density/process_genome.py", line 293, in <module>
    preprocessor.process()
  File "/Users/immlerlab/Documents/TE/TE_Density/transposon/preprocess.py", line 108, in process
    transposon_frame = self._revise_transposons(transposon_frame)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/immlerlab/Documents/TE/TE_Density/transposon/preprocess.py", line 189, in _revise_transposons
    te_data_unwrapped = revise_annotation(
                        ^^^^^^^^^^^^^^^^^^
  File "/Users/immlerlab/Documents/TE/TE_Density/transposon/verify_cache.py", line 168, in revise_annotation
    revised_te_data = ReviseAnno(
                      ^^^^^^^^^^^
  File "/Users/immlerlab/Documents/TE/TE_Density/transposon/revise_annotation.py", line 65, in __init__
    resource.setrlimit(resource.RLIMIT_STACK, (1000, -1))
ValueError: not allowed to raise maximum limit
make: *** [system_test] Error 1

I've tried manually setting the stack but that ddoesnt seem to help.

any ideas ? 

Johnny

**Comment by teresi** [comment]
I understand from a cursory investigation that `resource` module is not available on Windows.

Are you using Windows? (or maybe even WSL?)

Does the test succeed if you comment that line out?
