### ISSUE TITLE
Error "Unable to open object (object 'RHO_SUPERFAMILIES_RIGHT' doesn't exist)

### ISSUE THREAD

**Issue by PraveenOraon** [sjteresi/TE_Density#156]
Hi,
Thanks for developing a great tool with immense potential in scientific field.
I was trying to analyze TE density in my plant genome using your tool I got the following error while trying to retrive TE Density using general_read_density_data.py script. The error is as follow:
` python TE_Density/examples/general_read_density_data.py  '/Tools/TE_Data/Density/chr/chr2356.csv' /Tools/TE_Data/Density/chr/ 'SaffA2_(CtA_chr(\d{1,2}|[1-9]){1})_overlap.h5' 
2024-10-31 16:51:56 asus-server __main__[2951152] INFO import of preprocessed gene annotation... success!
2024-10-31 16:51:56 asus-server __main__[2951152] INFO 
            Using the user's provided regex string 'SaffA2_(CtA_chr(\d{1,2}|[1-9]){1})_overlap.h5' to match file
            objects and identify the proper pseudomolecule group for
            each file. Regex group 1 of this string must correspond to
            a pseudomolecule. This is needed to initialize DensityData.
            The user should verify that the pseudomolecule IDs derived from
            the GeneData correspond to the groups derived from the filename
            of the output .h5 data.
            
2024-10-31 16:51:56 asus-server __main__[2951152] INFO Pseudomolecule from GeneData is CtA_chr2, Regex group 1 of <re.Match object; span=(57, 83), match='SaffA2_CtA_chr2_overlap.h5'> is CtA_chr2
2024-10-31 16:51:56 asus-server __main__[2951152] INFO Pseudomolecule from GeneData is CtA_chr3, Regex group 1 of <re.Match object; span=(57, 83), match='SaffA2_CtA_chr3_overlap.h5'> is CtA_chr3
2024-10-31 16:51:56 asus-server __main__[2951152] INFO Pseudomolecule from GeneData is CtA_chr5, Regex group 1 of <re.Match object; span=(57, 83), match='SaffA2_CtA_chr5_overlap.h5'> is CtA_chr5
2024-10-31 16:51:56 asus-server __main__[2951152] INFO Pseudomolecule from GeneData is CtA_chr6, Regex group 1 of <re.Match object; span=(57, 83), match='SaffA2_CtA_chr6_overlap.h5'> is CtA_chr6
2024-10-31 16:51:56 asus-server __main__[2951152] INFO Writing new sense swapped DensityData...
Traceback (most recent call last):
  File "/Tools/TE_Density/examples/general_read_density_data.py", line 122, in <module>
    processed_dd_data = DensityData.from_list_gene_data_and_hdf5_dir(
  File "/Tools/TE_Density/transposon/density_data.py", line 498, in from_list_gene_data_and_hdf5_dir
    processed_dd_data = [
  File "/Tools/TE_Density/transposon/density_data.py", line 499, in <listcomp>
    cls(raw_hdf5_data_file, gene_data_obj, logger)
  File "/Tools/TE_Density/transposon/density_data.py", line 60, in __init__
    self._swap_strand_vals(genes_to_swap)
  File "/Tools/TE_Density/transposon/density_data.py", line 253, in _swap_strand_vals
    self.data_frame["RHO_SUPERFAMILIES_RIGHT"][:, :, index_to_switch],
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/miniconda3/envs/TE_Density/lib/python3.10/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'RHO_SUPERFAMILIES_RIGHT' doesn't exist)"
`
Kindly help me out in troubleshooting this error

Regards
Praveen

**Comment by sjteresi** [comment]
Hello,

Can you please post the output of `pip freeze` and double-check that you are using the correct version of each package as well as Python? I see that you are using Conda which is not directly supported, but you are using miniconda which would be the method I would suggest if you absolutely cannot use `pip`, so that is good.

Also can you please confirm you were able to get the system test to run without error?

Given the error you posted, it appears that either the pipeline did not finish correctly, or you have an issue with one of the h5py related packages and are having trouble accessing the data.
